--
-- PostgreSQL database dump
--

-- Dumped from database version 12.3
-- Dumped by pg_dump version 12.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: lines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lines (
    name text,
    speed double precision,
    color text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    coordinates text,
    map_id integer,
    id integer NOT NULL,
    service_windows text,
    layover double precision,
    hourly_cost integer,
    weekdays_per_year integer DEFAULT 255,
    saturdays_per_year integer DEFAULT 55,
    sundays_per_year integer DEFAULT 55
);


--
-- Name: lines_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.maps (
    id integer NOT NULL,
    name text,
    center text,
    zoom_level integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    remixed_from_id integer,
    layover double precision,
    hourly_cost integer,
    service_windows text,
    speed double precision,
    weekdays_per_year integer DEFAULT 255,
    saturdays_per_year integer DEFAULT 55,
    sundays_per_year integer DEFAULT 55,
    prefer_service_hours boolean,
    prefer_metric_units boolean DEFAULT false
);


--
-- Name: maps_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.maps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_info (
    version integer DEFAULT 0 NOT NULL
);


--
-- Name: lines lines_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lines
    ADD CONSTRAINT lines_pkey PRIMARY KEY (id);


--
-- Name: maps maps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maps
    ADD CONSTRAINT maps_pkey PRIMARY KEY (id);


--
-- Name: lines lines_map_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lines
    ADD CONSTRAINT lines_map_id_fkey FOREIGN KEY (map_id) REFERENCES public.maps(id);


--
-- PostgreSQL database dump complete
--

